import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0F172A',
  },
  container: {
    flexGrow: 1,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  pageShell: {
    width: '100%',
    alignItems: 'center',
    gap: 16,
  },
  hero: {
    width: '100%',
    alignItems: 'center',
    gap: 16,
  },
  heroDesktop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 20,
  },
  heroTextBlock: {
    alignItems: 'center',
  },
  heroTextBlockDesktop: {
    width: 280,
    alignItems: 'flex-start',
  },
  title: {
    color: '#F8FAFC',
    fontSize: 32,
    fontWeight: '800',
    marginBottom: 8,
  },
  titleDesktop: {
    fontSize: 40,
    marginBottom: 12,
  },
  subtitle: {
    color: '#CBD5E1',
    fontSize: 14,
    marginBottom: 24,
    textAlign: 'center',
  },
  subtitleDesktop: {
    textAlign: 'left',
    fontSize: 16,
    marginBottom: 0,
  },
  chartCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 24,
    backgroundColor: '#0B1120',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 18,
    paddingHorizontal: 14,
    shadowColor: '#020617',
    shadowOpacity: 0.3,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
    overflow: 'hidden',
  },
  chartCardDesktop: {
    flexGrow: 1,
    maxWidth: 520,
  },
  chartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    gap: 12,
  },
  chartEyebrow: {
    color: '#94A3B8',
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  chartTitle: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
  },
  chartPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(59, 130, 246, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.28)',
  },
  chartPillText: {
    color: '#BFDBFE',
    fontSize: 12,
    fontWeight: '700',
  },
  legendGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 10,
    marginBottom: 4,
  },
  legendItem: {
    minWidth: '46%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  legendCopy: {
    flex: 1,
  },
  legendLabel: {
    color: '#F8FAFC',
    fontSize: 13,
    fontWeight: '700',
  },
  legendValue: {
    color: '#94A3B8',
    fontSize: 12,
    marginTop: 1,
  },
  dropdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 14,
  },
  pressRow: {
    transform: [{ scale: 0.99 }],
    opacity: 0.92,
  },
  dropdownArrow: {
    color: '#F8FAFC',
    fontSize: 18,
    width: 20,
  },
  dropdownLabel: {
    color: '#F8FAFC',
    fontSize: 14,
    fontWeight: '700',
  },
  dropdownContent: {
    paddingLeft: 20,
    paddingBottom: 8,
  },
  dropdownText: {
    color: '#CBD5E1',
    fontSize: 13,
    marginTop: 4,
  },
  mapCard: {
    width: '100%',
    maxWidth: 420,
    marginTop: 16,
    borderRadius: 24,
    backgroundColor: 'rgba(17, 24, 39, 0.9)',
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  mapCardDesktop: {
    flexGrow: 1,
    maxWidth: 520,
    marginTop: 16,
  },
  map: {
    flex: 1,
    borderRadius: 18,
  },
  mapPlaceholder: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: '#0F172A',
  },
  loginCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 24,
    backgroundColor: 'rgba(17, 24, 39, 0.9)',
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  input: {
    height: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#334155',
    color: '#F8FAFC',
    paddingHorizontal: 14,
    marginBottom: 12,
    backgroundColor: '#0F172A',
  },
  loginError: {
    color: '#FCA5A5',
    fontSize: 13,
    marginBottom: 12,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 4,
  },
  secondaryButton: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(148, 163, 184, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#E2E8F0',
    fontSize: 15,
    fontWeight: '700',
  },
  loginButton: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#3B82F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
});